version: '3.9'

services:
  ranor-dashcam:
    build: .
    container_name: ranor-dashcam
    restart: unless-stopped
    network_mode: host          # usa host network para JT808 porta 808 sem root
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    # Se não quiser host network, use ports:
    # ports:
    #   - "808:808"     # JT808 (dashcam -> servidor)
    #   - "9999:9999"   # FTP snapshots
    #   - "8080:8080"   # Dashboard / API
